//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanvirattn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dayoff
    {
        public int id { get; set; }
        public int empid { get; set; }
        public string dayName { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string show { get; set; }
        public string active { get; set; }
        public int dayId { get; set; }
    }
}
