//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanvirattn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int empid { get; set; }
        public string EmployeeName { get; set; }
        public string DesignationId { get; set; }
    }
}
