//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanvirattn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday
    {
        public int HolidayId { get; set; }
        public string hoilidayName { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string show { get; set; }
        public int activityId { get; set; }
    }
}
