//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanvirattn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave
    {
        public int leaveId { get; set; }
        public string leaveType { get; set; }
        public System.DateTime date { get; set; }
        public int empid { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int HolidayId { get; set; }
        public int status { get; set; }
        public int leaveTypeId { get; set; }
    }
}
