//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanvirattn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_schedule
    {
        public long PersonalScheduleID { get; set; }
        public int empid { get; set; }
        public int scheduleid { get; set; }
        public System.DateTime ScheduleStart { get; set; }
        public System.DateTime SheduleEnd { get; set; }
        public int activityId { get; set; }
        public string show { get; set; }
    }
}
