//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanvirattn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_info
    {
        public int scheduleId { get; set; }
        public string ScheduleName { get; set; }
        public System.DateTime startTime { get; set; }
        public decimal start_bf { get; set; }
        public decimal start_af { get; set; }
        public System.DateTime end_time { get; set; }
        public decimal end_bf { get; set; }
        public decimal end_af { get; set; }
        public string activie { get; set; }
        public string show { get; set; }
    }
}
