//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tanvirattn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class attntfaEntities : DbContext
    {
        public attntfaEntities()
            : base("name=attntfaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dayName> dayNames { get; set; }
        public virtual DbSet<Dayoff> Dayoffs { get; set; }
        public virtual DbSet<designation> designations { get; set; }
        public virtual DbSet<emp> emps { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<leave> leaves { get; set; }
        public virtual DbSet<leave_Type> leave_Type { get; set; }
        public virtual DbSet<personal_schedule> personal_schedule { get; set; }
        public virtual DbSet<schedule_info> schedule_info { get; set; }
        public virtual DbSet<signature> signatures { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
